### ISSUE TITLE
Iframes still not showing up

### ISSUE THREAD

**Issue by kristajg** [vacenz/last-draft#23]
Hey @StevenIseki I put in a PR yesterday to fix the iframe issue... I saw you merged it (thanks!) but then made a series of subsequent changes which somehow brings me back to square one - still have problems with iframes in the editor.

 The iframes ARE saving (which is an improvement) but now they just plain don't show up in the editor anymore (they were at the time of my code getting merged - for now I am pointing to my forked branch since that is working with iframe insertion, but v1.3.0 is not).

**Comment by StevenIseki** [comment]
I think the issue here is just after merging your pr, I made a change to video plugin, it is now no longer added to Last Draft by default, instead there is a [ld-video plugin](https://github.com/vacenz/ld-video). This was in response to [this issue](https://github.com/vacenz/last-draft/issues/18). You now include `ld-video` as follows:

```js
import video from 'ld-video'
let plugins = [video, audio, color, emoji, html, todo]
```

I might reopen that issue for a little while so people can see the change and easily identify the issue.
