### ISSUE TITLE
All divs are converted to paragraphs tags in HTML editor

### ISSUE THREAD

**Issue by kristajg** [vacenz/last-draft#27]
Looks like every div tag from and to HTML is getting converted to a `<p>` tag. Nested divs looks end up looking like `<p><br></p>` this.  Making for some really strange looking formatting.

**Comment by kristajg** [comment]
Also FYI I think extra `<p>` tags are getting added around images / iframes

**Comment by StevenIseki** [comment]
On the paragraph tags issue e.g. `<div class='paragraph'>` which convert to html `<p>` I think this is how sstur's draft-js-export-to-html has the default tag set. It converts to `<p>` as default. This is pretty common with a lot of html editors like tinymce and others which have blocks as paragraphs. If you want you would just have to update the StateTOHTML function in convert folder, update the default to a div at line 260. This version in last-draft is just a slightly tweaked version of sstur's which adds support for custom entities, mainly Mentions.

**Comment by StevenIseki** [comment]
Your other issue, additional `<p>` tags around images is a bit tricky to fix, without losing focus after uploading an image. It has been discussed [here](https://github.com/globocom/megadraft/issues/92) as Last Draft uses the same function for adding atomic blocks.

**Comment by kristajg** [comment]
@StevenIseki This is rendering the html plugin rather unusable... if you pull in the INITIAL_STATE fromHTML, pull the html plugin into your plugins array, view in the browser, then open up the html option, then click the checkbox the formatting goes awry.  Please see gif of example:

 ![last-draft-bug convert-video-online com](https://cloud.githubusercontent.com/assets/2675535/23772300/1395a0d4-04e0-11e7-98d8-c4ac15cddaa1.gif)

**Comment by StevenIseki** [comment]
Hey @kristajg There was a small issue with html conversion. It was adding extra new lines for soft line breaks. I am not sure if this was causing your issue of multiple line breaks which it looks like in the gif above. Update to `2.0.1` for the fix to html conversion of line breaks.

As for your particular issue, `paragraph` tags are the default blocks and that is pretty common in an editor. In fact a paragraph and block of text are pretty analogous, whereas a div is more for layout. Draft uses divs in the editor with class paragraph which I suppose is inferring that each block should be rendered as `p` and with this being the default block type that would make sense.

Now you are wanting to go against this which is not recommended, but certainly is possible and should cause no issues. In fact all you need to do is update the default block type to `div` which I have shown in [this commit](https://github.com/vacenz/last-draft/commit/3d44f4b9340a62bce7fe6e8b03e2dcceaa696ba2). I have since removed this commit. You will just need to fork this repo and add those commits and use your fork version and you will be up and running.

**Comment by StevenIseki** [comment]
I have a screenshot here of this working perfectly fine with `div` as the default block type. So I will close this issue now.

![div fix](https://cloud.githubusercontent.com/assets/6695114/23851910/68330dfa-0839-11e7-8306-34d6f43b23b5.gif)
