### ISSUE TITLE
Copyright Holder

### ISSUE THREAD

**Issue by marcelometal** [vacenz/last-draft#9]
Hi @StevenIseki,

Could you please put the copyright holder and license inside each Megadraft's file? For the files you have modified, you can add a new copyright notice with your name.

Cheers!

**Comment by StevenIseki** [comment]
Hi @marcelometal I apologize for delaying this, I was still a bit unsure what to update.

In `v1.0.9` I have added the license [here](https://github.com/vacenz/last-draft/tree/master/src) and added the following copyright shown below to the following files, which were originally MegaDraft files and have now been modified:

```
src/index
src/utils/selection
src/utils/insertDataBlock
src/utils/entity
src/utils/convert
src/utils/block
src/plugins/block/*
src/plugins/image/*
src/plugins/video/*
src/decorators/defaultDecorator
src/components/Editor
src/components/Toolbar/*
src/components/Sidebar/*
src/components/Entities/Link
src/components/Buttons/*
src/components/Blocks/Media
src/actions/index
```

```
/*
 * Copyright (c) 2016, Globo.com (https://github.com/globocom)
 * Copyright (c) 2016, vace.nz (https://github.com/vacenz)
 *
 * License: MIT
 */
```

I have added the following to all the other files which were newly created:

```
/*
 * Copyright (c) 2016, vace.nz (https://github.com/vacenz)
 *
 * License: MIT
 */
```

All files have been modified at least a bit from the original source, mostly due to either restructuring or adding in the styled-components styles. 

I hope this is all correct now.

Once again thanks so much for your awesome work on Megadraft which last draft is extending on. If any updates you would like to use in MegaDraft feel free, or if you would like any pr's just let me know as this is also obviously MIT licensed. Thanks

**Comment by marcelometal** [comment]
Hi @StevenIseki, Thank you!
